version: '3.9'

services:
  api-service:
    container_name: api-container-1
    build:
      context: ./
      dockerfile: Dockerfile
#    environment:
#      API_TITLE: API DOC TEST
    env_file:
      - .env
    ports:
      - '8090:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge